# **Modul 3 - Dataset preparation mengggunakan panda**

##### 1. Masukkan iris.csv ke dataframe

In [ ]:
from google.colab import files
files.upload()

Saving iris.csv to iris.csv

{'iris.csv': b'"sepal.length","sepal.width","petal.length","petal.width","variety"\n5.1,3.5,1.4,.2,"Setosa"\n4.9,3,1.4,.2,"Setosa"\n4.7,3.2,1.3,.2,"Setosa"\n4.6,3.1,1.5,.2,"Setosa"\n5,3.6,1.4,.2,"Setosa"\n5.4,3.9,1.7,.4,"Setosa"\n4.6,3.4,1.4,.3,"Setosa"\n5,3.4,1.5,.2,"Setosa"\n4.4,2.9,1.4,.2,"Setosa"\n4.9,3.1,1.5,.1,"Setosa"\n5.4,3.7,1.5,.2,"Setosa"\n4.8,3.4,1.6,.2,"Setosa"\n4.8,3,1.4,.1,"Setosa"\n4.3,3,1.1,.1,"Setosa"\n5.8,4,1.2,.2,"Setosa"\n5.7,4.4,1.5,.4,"Setosa"\n5.4,3.9,1.3,.4,"Setosa"\n5.1,3.5,1.4,.3,"Setosa"\n5.7,3.8,1.7,.3,"Setosa"\n5.1,3.8,1.5,.3,"Setosa"\n5.4,3.4,1.7,.2,"Setosa"\n5.1,3.7,1.5,.4,"Setosa"\n4.6,3.6,1,.2,"Setosa"\n5.1,3.3,1.7,.5,"Setosa"\n4.8,3.4,1.9,.2,"Setosa"\n5,3,1.6,.2,"Setosa"\n5,3.4,1.6,.4,"Setosa"\n5.2,3.5,1.5,.2,"Setosa"\n5.2,3.4,1.4,.2,"Setosa"\n4.7,3.2,1.6,.2,"Setosa"\n4.8,3.1,1.6,.2,"Setosa"\n5.4,3.4,1.5,.4,"Setosa"\n5.2,4.1,1.5,.1,"Setosa"\n5.5,4.2,1.4,.2,"Setosa"\n4.9,3.1,1.5,.2,"Setosa"\n5,3.2,1.2,.2,"Setosa"\n5.5,3.5,1.3,.2,"Setosa"\n4.9,3.6,1.4,.1,"Setosa"\n4.4,3,1.3,.2,"Setosa"\n5.1,3.4,1.5,.2,"Setosa"\n5,3.5,1.3,.3,"Setosa"\n4.5,2.3,1.3,.3,"Setosa"\n4.4,3.2,1.3,.2,"Setosa"\n5,3.5,1.6,.6,"Setosa"\n5.1,3.8,1.9,.4,"Setosa"\n4.8,3,1.4,.3,"Setosa"\n5.1,3.8,1.6,.2,"Setosa"\n4.6,3.2,1.4,.2,"Setosa"\n5.3,3.7,1.5,.2,"Setosa"\n5,3.3,1.4,.2,"Setosa"\n7,3.2,4.7,1.4,"Versicolor"\n6.4,3.2,4.5,1.5,"Versicolor"\n6.9,3.1,4.9,1.5,"Versicolor"\n5.5,2.3,4,1.3,"Versicolor"\n6.5,2.8,4.6,1.5,"Versicolor"\n5.7,2.8,4.5,1.3,"Versicolor"\n6.3,3.3,4.7,1.6,"Versicolor"\n4.9,2.4,3.3,1,"Versicolor"\n6.6,2.9,4.6,1.3,"Versicolor"\n5.2,2.7,3.9,1.4,"Versicolor"\n5,2,3.5,1,"Versicolor"\n5.9,3,4.2,1.5,"Versicolor"\n6,2.2,4,1,"Versicolor"\n6.1,2.9,4.7,1.4,"Versicolor"\n5.6,2.9,3.6,1.3,"Versicolor"\n6.7,3.1,4.4,1.4,"Versicolor"\n5.6,3,4.5,1.5,"Versicolor"\n5.8,2.7,4.1,1,"Versicolor"\n6.2,2.2,4.5,1.5,"Versicolor"\n5.6,2.5,3.9,1.1,"Versicolor"\n5.9,3.2,4.8,1.8,"Versicolor"\n6.1,2.8,4,1.3,"Versicolor"\n6.3,2.5,4.9,1.5,"Versicolor"\n6.1,2.8,4.7,1.2,"Versicolor"\n6.4,2.9,4.3,1.3,"Versicolor"\n6.6,3,4.4,1.4,"Versicolor"\n6.8,2.8,4.8,1.4,"Versicolor"\n6.7,3,5,1.7,"Versicolor"\n6,2.9,4.5,1.5,"Versicolor"\n5.7,2.6,3.5,1,"Versicolor"\n5.5,2.4,3.8,1.1,"Versicolor"\n5.5,2.4,3.7,1,"Versicolor"\n5.8,2.7,3.9,1.2,"Versicolor"\n6,2.7,5.1,1.6,"Versicolor"\n5.4,3,4.5,1.5,"Versicolor"\n6,3.4,4.5,1.6,"Versicolor"\n6.7,3.1,4.7,1.5,"Versicolor"\n6.3,2.3,4.4,1.3,"Versicolor"\n5.6,3,4.1,1.3,"Versicolor"\n5.5,2.5,4,1.3,"Versicolor"\n5.5,2.6,4.4,1.2,"Versicolor"\n6.1,3,4.6,1.4,"Versicolor"\n5.8,2.6,4,1.2,"Versicolor"\n5,2.3,3.3,1,"Versicolor"\n5.6,2.7,4.2,1.3,"Versicolor"\n5.7,3,4.2,1.2,"Versicolor"\n5.7,2.9,4.2,1.3,"Versicolor"\n6.2,2.9,4.3,1.3,"Versicolor"\n5.1,2.5,3,1.1,"Versicolor"\n5.7,2.8,4.1,1.3,"Versicolor"\n6.3,3.3,6,2.5,"Virginica"\n5.8,2.7,5.1,1.9,"Virginica"\n7.1,3,5.9,2.1,"Virginica"\n6.3,2.9,5.6,1.8,"Virginica"\n6.5,3,5.8,2.2,"Virginica"\n7.6,3,6.6,2.1,"Virginica"\n4.9,2.5,4.5,1.7,"Virginica"\n7.3,2.9,6.3,1.8,"Virginica"\n6.7,2.5,5.8,1.8,"Virginica"\n7.2,3.6,6.1,2.5,"Virginica"\n6.5,3.2,5.1,2,"Virginica"\n6.4,2.7,5.3,1.9,"Virginica"\n6.8,3,5.5,2.1,"Virginica"\n5.7,2.5,5,2,"Virginica"\n5.8,2.8,5.1,2.4,"Virginica"\n6.4,3.2,5.3,2.3,"Virginica"\n6.5,3,5.5,1.8,"Virginica"\n7.7,3.8,6.7,2.2,"Virginica"\n7.7,2.6,6.9,2.3,"Virginica"\n6,2.2,5,1.5,"Virginica"\n6.9,3.2,5.7,2.3,"Virginica"\n5.6,2.8,4.9,2,"Virginica"\n7.7,2.8,6.7,2,"Virginica"\n6.3,2.7,4.9,1.8,"Virginica"\n6.7,3.3,5.7,2.1,"Virginica"\n7.2,3.2,6,1.8,"Virginica"\n6.2,2.8,4.8,1.8,"Virginica"\n6.1,3,4.9,1.8,"Virginica"\n6.4,2.8,5.6,2.1,"Virginica"\n7.2,3,5.8,1.6,"Virginica"\n7.4,2.8,6.1,1.9,"Virginica"\n7.9,3.8,6.4,2,"Virginica"\n6.4,2.8,5.6,2.2,"Virginica"\n6.3,2.8,5.1,1.5,"Virginica"\n6.1,2.6,5.6,1.4,"Virginica"\n7.7,3,6.1,2.3,"Virginica"\n6.3,3.4,5.6,2.4,"Virginica"\n6.4,3.1,5.5,1.8,"Virginica"\n6,3,4.8,1.8,"Virginica"\n6.9,3.1,5.4,2.1,"Virginica"\n6.7,3.1,5.6,2.4,"Virginica"\n6.9,3.1,5.1,2.3,"Virginica"\n5.8,2.7,5.1,1.9,"Virginica"\n6.8,3.2,5.9,2.3,"Virginica"\n6.7,3.3,5.7,2.5,"Virginica"\n6.7,3,5.2,2.3,"Virginica"\n6.3,2.5,5,1.9,"Virginica"\n6.5,3,5.2,2,"Virginica"\n6.2,3.4,5.4,2.3,"Virginica"\n5.9,3,5.1,1.8,"Virginica"'}

In [ ]:
import pandas as pd

df = pd.read_csv('iris.csv')
df_copy = df.copy()
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

##### 2. Normalisasikan setiap attribut iris ke dataframe menggunakan normalisasi min max sehingga setiap nilai attribut memiliki range 0 – 1. Vbaru = (Vlama - Vmin) / (Vmax - Vmin). Vbaru = nilai data di suatu sel setelah normalisasi, Vlama = nilai data asli sebelum normalisasi, Vmax = nilai max dari kolom data tersebut, Vmin = nilai min dari kolom data tersebut

In [ ]:
def normalize(columns):
  return (df_copy[columns] - df_copy[columns].min()) / (df_copy[columns].max() - df_copy[columns].min())

In [ ]:
columns = df.columns[:4]
for i in columns:
  df_copy[i] = normalize(i)

df_normalize = df_copy
df_normalize

     sepal.length  sepal.width  petal.length  petal.width    variety
0        0.222222     0.625000      0.067797     0.041667     Setosa
1        0.166667     0.416667      0.067797     0.041667     Setosa
2        0.111111     0.500000      0.050847     0.041667     Setosa
3        0.083333     0.458333      0.084746     0.041667     Setosa
4        0.194444     0.666667      0.067797     0.041667     Setosa
..            ...          ...           ...          ...        ...
145      0.666667     0.416667      0.711864     0.916667  Virginica
146      0.555556     0.208333      0.677966     0.750000  Virginica
147      0.611111     0.416667      0.711864     0.791667  Virginica
148      0.527778     0.583333      0.745763     0.916667  Virginica
149      0.444444     0.416667      0.694915     0.708333  Virginica

[150 rows x 5 columns]

##### 3. Cari centroid dari data yang telah dinormalisasi. Centroid dihitung dari rata2 seluruh data suatu kolom

In [ ]:
def centroid(df_normalize, var):
  centroid = df_normalize[df_normalize["variety"] == var].iloc[:, :4].mean()
  return centroid

In [ ]:
variety = df_normalize["variety"].unique()
variety

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [ ]:
center = {}

for i in variety:
  center['centroid_{0}'.format(i)] = centroid(df_normalize, i)

In [ ]:
centroid = pd.DataFrame(center)
centroid

              centroid_Setosa  centroid_Versicolor  centroid_Virginica
sepal.length         0.196111             0.454444            0.635556
sepal.width          0.595000             0.320833            0.405833
petal.length         0.078305             0.552542            0.771525
petal.width          0.060833             0.510833            0.802500

##### 4. Masukkan iristesting.csv ke dataframe. Normalisasikan iristesting.csv menggunakan vmin dan vmax pada data 1

In [ ]:
from google.colab import files
files.upload()

Saving iristesting.csv to iristesting.csv

{'iristesting.csv': b'"sepal.length","sepal.width","petal.length","petal.width","variety"\r\n5,3.5,1.3,0.3,Setosa\r\n4.5,2.3,1.3,0.3,Setosa\r\n4.4,3.2,1.3,0.2,Setosa\r\n5,3.5,1.6,0.6,Setosa\r\n5.1,3.8,1.9,0.4,Setosa\r\n4.8,3,1.4,0.3,Setosa\r\n5.1,3.8,1.6,0.2,Setosa\r\n4.6,3.2,1.4,0.2,Setosa\r\n5.3,3.7,1.5,0.2,Setosa\r\n5,3.3,1.4,0.2,Setosa\r\n5.5,2.6,4.4,1.2,Versicolor\r\n6.1,3,4.6,1.4,Versicolor\r\n5.8,2.6,4,1.2,Versicolor\r\n5,2.3,3.3,1,Versicolor\r\n5.6,2.7,4.2,1.3,Versicolor\r\n5.7,3,4.2,1.2,Versicolor\r\n5.7,2.9,4.2,1.3,Versicolor\r\n6.2,2.9,4.3,1.3,Versicolor\r\n5.1,2.5,3,1.1,Versicolor\r\n5.7,2.8,4.1,1.3,Versicolor\r\n6.7,3.1,5.6,2.4,Virginica\r\n6.9,3.1,5.1,2.3,Virginica\r\n5.8,2.7,5.1,1.9,Virginica\r\n6.8,3.2,5.9,2.3,Virginica\r\n6.7,3.3,5.7,2.5,Virginica\r\n6.7,3,5.2,2.3,Virginica\r\n6.3,2.5,5,1.9,Virginica\r\n6.5,3,5.2,2,Virginica\r\n6.2,3.4,5.4,2.3,Virginica\r\n5.9,3,5.1,1.8,Virginica\r\n'}

In [ ]:
df_test = pd.read_csv('iristesting.csv')
df_test.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.0          3.5           1.3          0.3  Setosa
1           4.5          2.3           1.3          0.3  Setosa
2           4.4          3.2           1.3          0.2  Setosa
3           5.0          3.5           1.6          0.6  Setosa
4           5.1          3.8           1.9          0.4  Setosa

In [ ]:
def normalize_test(columns):
  return (df_test[columns] - df_test[columns].min()) / (df_test[columns].max() - df_test[columns].min())

columns = df_test.columns[:4]
for i in columns:
  df_test[i] = normalize_test(i)

df_normalize_test = df_test
df_normalize_test.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0          0.24          0.8      0.000000     0.043478  Setosa
1          0.04          0.0      0.000000     0.043478  Setosa
2          0.00          0.6      0.000000     0.000000  Setosa
3          0.24          0.8      0.065217     0.173913  Setosa
4          0.28          1.0      0.130435     0.086957  Setosa

##### 5. Prediksilah kelas data di iristesting.csv menggunakan kriteria kedekatan distance antara setiap data di iristesting.csv ke centroid masing2 class di iris. Gunakan euclidean distance

In [ ]:
def distance(df_normalize_test, centroid):
  distance = 0
  for i in centroid.index:
    distance += (df_normalize_test[i] - centroid[i])**2
  distance_result = distance**(1/2)
  return distance_result

def predict (x, y):
  variety = df_normalize_test["variety"].unique()
  data_sum = len(x[variety[0]])
  result = []

  true = 0
  false = 0
  for i in range(data_sum):
    compare = []
    for j in variety:
      compare.append(x[j][i])
    index_compare = compare.index(min(compare))
    prediction = variety[index_compare]
    result.append(prediction)

    if prediction == y[i]:
      print("True")
      true += 1
    else:
      print("False")
      false += 1
  return {"result": result,
          "correct": true,
          "wrong": false}

setosa_pred = []
versicolor_pred = []
virginica_pred = []
y = df_normalize_test["variety"]

for i, row in df_normalize_test.iterrows():
  setosa = distance(row, center["centroid_Setosa"])
  versicolor = distance(row, center["centroid_Versicolor"])
  virginica = distance(row, center["centroid_Virginica"])

  setosa_pred.append(setosa)
  versicolor_pred.append(versicolor)
  virginica_pred.append(virginica)

x = {
    "Setosa": setosa_pred,
    "Versicolor": versicolor_pred,
    "Virginica": virginica_pred
}

prediction_result = predict(x, y)

True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True

##### 6. Hitunglah berapa persen klasifikasi yang benar (akurasi) saat memprediksi class

In [ ]:
correct = prediction_result['correct']
wrong = prediction_result['wrong']
accuracy = correct/(correct + wrong)*100

print(f"Total data    : {correct + wrong}"
      f"\nPrediksi benar: {correct}"
      f"\nPrediksi salah: {wrong}"
      f"\nAccuracy      : {round(accuracy, 2)} %")

Total data    : 30
Prediksi benar: 29
Prediksi salah: 1
Accuracy      : 96.67 %